FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

EXPOSE 10000

CMD ["streamlit", "run", "src/infrastructure/dashboard/streamlit_dashboard.py", "--server.port=10000", "--server.address=0.0.0.0"]